# Funding options for PACE pattern development
# Uncomment and configure as needed

# github: semanticintent
# patreon: username
# open_collective: pace-pattern
# ko_fi: username
# custom: ["https://semanticintent.dev/sponsor"]
